/**
 * Normalized token usage and cost.
 *
 * Providers report usage in their own vocabulary (the Claude Agent SDK uses
 * snake_case `input_tokens` / `cache_read_input_tokens` and a separate
 * `modelUsage` map). Adapters translate into these camelCase, provider-neutral
 * shapes so the UI has exactly one thing to render.
 */

import type { ProfileId } from './ids.js';
import type { PlanCapacity, ResolvedPlanWeight } from './planCapacity.js';
import { reservationFor, type LiveRunLoad } from './planLoad.js';
import type { ProviderId } from './provider.js';

/**
 * Token counts for a run, a turn or a single model.
 *
 * Every field is optional except {@link inputTokens} and {@link outputTokens}:
 * providers without prompt caching or server-side tools simply omit the rest.
 * Counts are absolute for the scope they describe, never percentages.
 */
export interface TokenUsage {
  /** Uncached input tokens billed at the full rate. */
  readonly inputTokens: number;
  /** Tokens generated by the model, including thinking tokens. */
  readonly outputTokens: number;
  /** Input tokens served from the prompt cache. */
  readonly cacheReadInputTokens?: number;
  /** Input tokens written into the prompt cache this turn. */
  readonly cacheCreationInputTokens?: number;
  /** Server-side tool invocations (e.g. web search) billed separately. */
  readonly webSearchRequests?: number;
}

/** Per-model usage, keyed by the provider's model identifier. */
export interface ModelTokenUsage extends TokenUsage {
  /** The model this row is for, as the provider names it. */
  readonly model: string;
  /** Cost attributable to this model, when the provider prices it. */
  readonly costUsd?: number;
  /** Total context window for this model, if reported. */
  readonly contextWindow?: number;
}

/**
 * How to interpret the numbers on a `usage` event.
 *
 * - `delta`      — usage incurred since the previous `usage` event.
 * - `cumulative` — running total for the whole run so far.
 * - `final`      — the authoritative total, emitted alongside `run.end`.
 *
 * Adapters must pick one convention per provider and stick to it. A UI that
 * sums `cumulative` events, or that replaces state on `delta` events, will
 * display nonsense — so the scope is on the wire rather than assumed.
 */
export type UsageScope = 'delta' | 'cumulative' | 'final';

/**
 * A usage snapshot.
 *
 * `contextTokens` / `contextWindow` describe how full the conversation's
 * context is right now, which is a different question from how many tokens
 * have been billed; both matter to the UI, so both are carried.
 */
export interface UsageSnapshot {
  readonly scope: UsageScope;
  readonly tokens: TokenUsage;
  /** Cost in US dollars, when the provider prices the request. */
  readonly costUsd?: number;
  /** Breakdown by model, when more than one model served the run. */
  readonly byModel?: readonly ModelTokenUsage[];
  /** Tokens currently occupying the context window. */
  readonly contextTokens?: number;
  /** Size of the context window the run is using. */
  readonly contextWindow?: number;
}

/* -------------------------------------------------------------------------- */
/* Plan usage — consumption against a subscription's limits                    */
/* -------------------------------------------------------------------------- */

/**
 * One rate-limit window.
 *
 * A percentage rather than a token count, because that is what the provider
 * publishes: plan limits are not a simple token budget, and inventing an
 * absolute number from a percentage would be a guess presented as a fact.
 */
export interface PlanUsageWindow {
  /** Stable identifier for the window, e.g. `five_hour`. */
  readonly id: PlanUsageWindowId;
  /** Human-readable name for the window, e.g. "5 hours". */
  readonly label: string;
  /** Share of the window consumed, 0–100. `null` when the provider omits it. */
  readonly utilization: number | null;
  /** When the window rolls over, ms since epoch. `null` when not reported. */
  readonly resetsAt: number | null;
  /**
   * The provider's own verdict on this window, when one has been heard.
   *
   * This is the field that stops "97% but out". The percentage is a rounded,
   * minutes-old reading; the verdict is the server saying what it is actually
   * doing with requests right now, and where the two disagree the verdict is
   * the truth. Absent when nothing live has been heard — a window from the
   * polled snapshot alone carries only its number.
   */
  readonly status?: PlanLimitStatus;
}

/**
 * What the provider is doing with requests against a limit.
 *
 * - `ok`       — requests are being served normally.
 * - `warning`  — served, but the provider says the limit is close.
 * - `rejected` — refused. The window is spent regardless of what its
 *                percentage reads; a rejected window at 97% is *out*, not
 *                "3% from out".
 */
export type PlanLimitStatus = 'ok' | 'warning' | 'rejected';

/**
 * One live report about one limit, as an event mid-run carries it.
 *
 * This is the payload of a `plan.limit` agent event, defined here rather than
 * in `events.ts` because {@link applyPlanLimit} consumes it and `usage.ts`
 * cannot import the event union without a cycle.
 *
 * Everything but the verdict is optional because the provider's live signal is
 * a health report, not a gauge reading: the common case carries a status and a
 * window name and *no percentage at all*.
 */
export interface PlanLimitReading {
  /** The verdict. The one field a reading is worthless without. */
  readonly status: PlanLimitStatus;
  /** Which window the verdict is about. Absent when the provider names none. */
  readonly windowId?: PlanUsageWindowId;
  /** Display label for {@link windowId}, when the adapter knows one. */
  readonly label?: string;
  /** Share of the window consumed, 0–100, when the report carries it. */
  readonly utilization?: number;
  /** When the window rolls over, ms since epoch, when the report carries it. */
  readonly resetsAt?: number;
}

/**
 * Fold a live limit report into the last polled snapshot.
 *
 * Returns the merged snapshot, or `null` when the reading is not news — and
 * `null` matters as much as the merge does. The provider sends a report on
 * every API response, which during a fanned-out workflow is many per second;
 * a caller broadcasts what this returns, so everything that would only restate
 * the cache must come back `null` or the push channel becomes a firehose of
 * no-ops. News is a verdict changing or a percentage moving, and nothing else:
 *
 *  - A reset time is deliberately *not* news by itself. Every report carries
 *    one, at second precision, while the poll records the same instant at
 *    sub-millisecond precision — treating the difference as change would make
 *    every report newsworthy forever. It rides along when something else is.
 *  - An `ok` report is news only when it *clears* a worse verdict already
 *    held. That case is common and load-bearing: a 5-hour window rolling over
 *    mid-session is exactly an `ok` arriving on a window marked `rejected`.
 *  - A reading naming no window is never news. The verdict cannot be attached
 *    to a window it might not belong to, and every observed payload names one.
 *
 * The merge keeps what it is not contradicted on: a report with no percentage
 * leaves the polled percentage standing rather than blanking it.
 *
 * `fetchedAt` is stamped on the merged snapshot because the *verdict* is
 * fresh, even though any untouched percentages are as old as the poll that
 * read them. While reports are arriving the active-profile poll re-reads the
 * numbers every thirty seconds, which bounds how far the two can drift.
 *
 * Note the complement: a later poll replaces the snapshot wholesale and drops
 * any held verdict. That is self-healing, not loss — a verdict with no run
 * feeding it fresh evidence goes stale the moment the window rolls, and the
 * poll's numbers are the better fact within minutes either way.
 */
export function applyPlanLimit(
  usage: PlanUsage | null | undefined,
  reading: PlanLimitReading,
  fetchedAt: number,
): PlanUsage | null {
  const windowId = reading.windowId;
  if (windowId === undefined) return null;

  // An unavailable snapshot ("no plan limits apply") is *not* merged into: a
  // live verdict arriving on such a profile means the provider disagrees with
  // it, so it is replaced by a minimal available one the same way no snapshot
  // at all would be.
  const existing = usage?.available === true ? usage : null;
  const current = existing?.windows.find((w) => w.id === windowId) ?? null;

  const statusChanged = reading.status !== (current?.status ?? 'ok');
  const utilizationMoved =
    reading.utilization !== undefined && reading.utilization !== current?.utilization;
  if (!statusChanged && !utilizationMoved) return null;

  const window: PlanUsageWindow = {
    id: windowId,
    // The polled label wins: it is the vocabulary the rest of the UI already
    // shows, and a reading's label is a fallback for a window the poll has
    // never reported.
    label: current?.label ?? reading.label ?? windowId.replace(/_/g, ' '),
    utilization: reading.utilization ?? current?.utilization ?? null,
    resetsAt: reading.resetsAt ?? current?.resetsAt ?? null,
    status: reading.status,
  };

  const windows =
    current === null
      ? [...(existing?.windows ?? []), window]
      : existing?.windows.map((w) => (w.id === windowId ? window : w)) ?? [window];

  return {
    available: true,
    windows,
    fetchedAt,
    ...(existing?.subscriptionType === undefined
      ? {}
      : { subscriptionType: existing.subscriptionType }),
  };
}

/**
 * The windows a plan can be limited by.
 *
 * Open-ended on purpose: plans gain and lose windows, and an adapter that meets
 * an unfamiliar one should pass it through rather than drop it on the floor.
 */
export type PlanUsageWindowId =
  | 'five_hour'
  | 'seven_day'
  | 'seven_day_opus'
  | 'seven_day_sonnet'
  | 'seven_day_oauth_apps'
  | 'model_scoped'
  | 'extra_usage'
  | 'spend'
  | (string & {});

/**
 * A profile's consumption against its plan limits.
 *
 * Distinct from {@link UsageSnapshot}, which describes one run. This describes
 * the *account*: how much of the plan's capacity is gone and when it comes
 * back.
 *
 * `available: false` is a first-class, expected state rather than an error —
 * plan limits simply do not apply to API-key, Bedrock, Vertex or Foundry
 * billing, where usage is metered instead of capped. Callers should render the
 * `unavailableReason` rather than an empty meter, so the difference between
 * "nothing used" and "not applicable" is visible.
 */
export interface PlanUsage {
  readonly available: boolean;
  /** Why there is nothing to show. Present only when `available` is false. */
  readonly unavailableReason?: string;
  /** Plan tier as the provider names it, e.g. `pro`, `max`. */
  readonly subscriptionType?: string;
  /** Windows the plan is limited by, in display order. Empty when unavailable. */
  readonly windows: readonly PlanUsageWindow[];
  /** When this snapshot was taken, ms since epoch. Drives the staleness hint. */
  readonly fetchedAt: number;
}

/**
 * The most-consumed window, which is the one that will actually stop you.
 *
 * A plan with several windows is limited by whichever is closest to full, so a
 * single-glance indicator should show that one rather than an average — an
 * average of "5% of weekly, 98% of 5-hourly" reads as comfortable when you are
 * about to be cut off.
 */
/**
 * A window a compact readout can ask for by name.
 *
 * The three the status bar draws a ring for. It was a *setting* once — one bar
 * counted down one of these — and is now simply the vocabulary for asking, since
 * all three are on screen at the same time.
 *
 * `model` is a family rather than one id: the per-model buckets a plan meters
 * separately vary by account (`model_scoped:Fable` and friends), so the request
 * has to name the family and let {@link focusedWindow} pick within it.
 */
export type PlanMeterFocus = 'five_hour' | 'seven_day' | 'model';

/** True for the per-model weekly buckets. @see PlanMeterFocus */
export function isModelScoped(id: string): boolean {
  return id === 'model_scoped' || id.startsWith('model_scoped:');
}

/**
 * The window a meter set to `focus` should report, or `null` if the plan has
 * no such window.
 *
 * Within the `model` family the most-consumed bucket wins, for the same reason
 * {@link bindingWindow} exists: the one closest to full is the one that will
 * stop you, and averaging several models' weeklies would describe none of them.
 *
 * Note this answers *only* the chosen window. A plan can be comfortable on the
 * focused one and nearly out on another, so the number here is not a promise
 * that nothing is about to run out — that is what the full list is for.
 */
export function focusedWindow(
  usage: PlanUsage | null | undefined,
  focus: PlanMeterFocus,
): PlanUsageWindow | null {
  if (!usage?.available) return null;
  if (focus === 'model') {
    let worst: PlanUsageWindow | null = null;
    for (const window of usage.windows) {
      if (!isModelScoped(window.id) || window.utilization === null) continue;
      if (worst === null || window.utilization > (worst.utilization ?? -1)) worst = window;
    }
    return worst;
  }
  return usage.windows.find((w) => w.id === focus) ?? null;
}

export function bindingWindow(usage: PlanUsage | null | undefined): PlanUsageWindow | null {
  if (!usage?.available) return null;
  // A window the provider has said it is rejecting on outranks any percentage:
  // it is the limit that is stopping you as a fact, not a forecast. It binds
  // even with no percentage at all — the number a rejected window lacks is not
  // evidence that some 40% window is the tighter constraint.
  let rejected: PlanUsageWindow | null = null;
  let worst: PlanUsageWindow | null = null;
  for (const window of usage.windows) {
    if (window.status === 'rejected') {
      if (rejected === null || (window.utilization ?? -1) > (rejected.utilization ?? -1)) {
        rejected = window;
      }
      continue;
    }
    if (window.utilization === null) continue;
    if (worst === null || window.utilization > (worst.utilization ?? -1)) worst = window;
  }
  return rejected ?? worst;
}

/** One window a compact readout draws, under the short name it draws it with. */
export interface PlanMeterSlot {
  readonly id: string;
  /** `5hr`, `Week`, `Fable` — or the provider's own label on a plan with none of those. */
  readonly label: string;
  readonly window: PlanUsageWindow;
}

/**
 * The windows a glanceable readout draws, in order.
 *
 * The 5-hour limit, the weekly limit and Fable's own weekly bucket: the three
 * worth watching without opening anything, and the same three on every
 * surface — the desktop's status bar, its run navigator, the terminal's line
 * under the composer — so no two of them disagree about which windows earn a
 * place. Fable is matched by name, and only by name: it is the expensive
 * model, metered apart from the plan total, and on an account that leans on
 * it the limit that goes first. A plan that meters some other model gets two
 * slots rather than a third standing in — a slot is a position you learn, and
 * one whose subject changes with the account is a number you have to read the
 * label to trust. The match is case-insensitive because the name is the
 * provider's `display_name` verbatim: presentation, not an identifier.
 *
 * A window the plan does not report is *skipped* rather than drawn empty —
 * "this plan has no weekly limit" must not read as "you have used none of
 * it" — so this is up to three slots. Where none of the three exist, the
 * window closest to full stands alone under the provider's own name, so a
 * provider with its own vocabulary still shows a real number.
 */
export function planMeterSlots(usage: PlanUsage | null | undefined): readonly PlanMeterSlot[] {
  if (!usage?.available) return [];
  const slots: PlanMeterSlot[] = [];

  const fiveHour = focusedWindow(usage, 'five_hour');
  if (fiveHour !== null) slots.push({ id: fiveHour.id, label: '5hr', window: fiveHour });

  const week = focusedWindow(usage, 'seven_day');
  if (week !== null) slots.push({ id: week.id, label: 'Week', window: week });

  const fable = usage.windows.find(
    (w) => isModelScoped(w.id) && w.id.slice('model_scoped:'.length).toLowerCase() === 'fable',
  );
  if (fable !== undefined) slots.push({ id: fable.id, label: 'Fable', window: fable });

  if (slots.length > 0) return slots;

  const binding = bindingWindow(usage);
  return binding === null ? [] : [{ id: binding.id, label: binding.label, window: binding }];
}

/* -------------------------------------------------------------------------- */
/* Headroom — which account has room left                                      */
/* -------------------------------------------------------------------------- */

/**
 * How often plan usage is re-read for every profile.
 *
 * A compromise between two real costs. A reading is only meaningful for minutes
 * — a long turn can move the 5-hour window several points — so polling slower
 * recommends an account on numbers that have moved. But each reading spawns the
 * provider's CLI, once per profile, so polling faster puts a steady drip of
 * subprocesses on the machine for a figure nobody is looking at most of the
 * time.
 *
 * Two minutes rather than the five it was. Automatic handoff reads these
 * numbers to decide when to stop, and at five minutes a window could cross its
 * threshold and stay uncrossed as far as Artemis knew for the length of several
 * turns — which is long enough to hit the wall the feature exists to stop short
 * of. The cost is paid where it is cheap: the sweep skips profiles nothing is
 * running on, so an idle machine polls no harder than before.
 *
 * Lives here rather than in the poller because the renderer needs it too: it is
 * what {@link PLAN_USAGE_MAX_AGE_MS} is defined in terms of.
 */
export const PLAN_USAGE_POLL_INTERVAL_MS = 2 * 60_000;

/**
 * How often the profile of a *live run* is re-read.
 *
 * The account being spent is the only one whose number can move on its own, and
 * it is the one a handoff decision is about. Polling it on the full sweep's
 * cadence means deciding on a reading up to two minutes old, taken before the
 * turn that has been running ever since.
 *
 * Thirty seconds is affordable precisely because it is not the sweep: one CLI
 * for the accounts with work on them, rather than one per profile. A machine
 * with eight profiles and one live run pays for one reading, not eight.
 */
export const PLAN_USAGE_ACTIVE_POLL_INTERVAL_MS = 30_000;

/**
 * How old a reading may be and still be worth recommending on.
 *
 * Three missed polls, expressed as such rather than as a number of its own so
 * that tightening the poll tightens this with it. The poll is the only thing
 * that keeps these figures current, and it can stall for reasons the renderer
 * cannot see — the machine slept, a CLI hung, the provider stopped answering. A
 * recommendation is a claim about *right now*, so it expires rather than
 * quietly ageing: an account named on numbers that old may have been drained
 * since by another window, another machine, or the user's own terminal.
 *
 * Note this governs the *recommendation* only. A stale reading is still worth
 * showing in a meter, where it carries its own "4m ago" — the difference is
 * that the meter reports and the recommendation advises.
 */
export const PLAN_USAGE_MAX_AGE_MS = 3 * PLAN_USAGE_POLL_INTERVAL_MS;

/**
 * How much of a plan is left, as a percentage of its tightest window.
 *
 * The complement of {@link bindingWindow}, and it uses that window rather than
 * an average for the same reason: a plan is as free as its most-consumed limit,
 * so an account at 5% weekly and 98% five-hourly has 2% of room, not 48%.
 *
 * `null` when there is nothing to answer from — no reading, no plan limits, or
 * a plan whose windows all report `null` utilization. That is distinct from
 * `0`, which is a plan that is genuinely full.
 */
export function planHeadroom(usage: PlanUsage | null | undefined): number | null {
  const binding = bindingWindow(usage);
  if (binding === null) return null;
  // A rejected window is zero headroom whatever its percentage reads — the
  // provider is refusing requests, and "3% left" on a window that is already
  // refusing is the lie this field exists to correct.
  if (binding.status === 'rejected') return 0;
  if (binding.utilization === null) return null;
  return 100 - binding.utilization;
}

/** One profile's latest reading, as {@link recommendProfile} takes them. */
export interface ProfilePlanUsage {
  readonly profileId: ProfileId;
  readonly usage: PlanUsage | null | undefined;
  /**
   * Which provider the account belongs to. Required for weighting: plan weights
   * are ratios against *that provider's* baseline plan, and are meaningless
   * across two. See {@link PlanCapacity}.
   */
  readonly providerId?: ProviderId;
  /**
   * How large this plan is next to its provider's baseline, from
   * {@link resolvePlanWeight}. Omitted, or `null` inside, when the plan
   * publishes no such ratio — Team and Enterprise meter per seat or against a
   * contract pool and are not sold as a multiple of anything.
   */
  readonly capacity?: ResolvedPlanWeight | null;
  /**
   * Runs already going on this account, which its reading does not yet show.
   *
   * The correction for a chooser reading a lagging measurement — see
   * `planLoad.ts` for the herd this exists to break. Absent or empty means an
   * idle account, which is the ordinary case and reserves nothing.
   */
  readonly liveRuns?: readonly LiveRunLoad[];
}

/**
 * What the ranking was actually able to compare, weakest claim last.
 *
 * The section's wording turns on this, and getting it wrong is a confident lie
 * about someone's billing:
 *
 * - `same-plan`  — every candidate is on one plan, so percentages describe one
 *                  ceiling and the winner genuinely has the most room.
 * - `weighted`   — the plans differ but every one publishes its size relative to
 *                  its provider's baseline, so headroom is scaled by that ratio
 *                  and the winner has the most *capacity*. See
 *                  {@link PLAN_CAPACITIES} for what "published" is allowed to
 *                  mean here.
 * - `percentage` — at least one plan publishes no ratio (Team, Enterprise), or
 *                  the candidates span two providers whose baselines have no
 *                  published rate between them. The ranking still happens and is
 *                  still useful; it is a ranking of shares, and the UI must say
 *                  so rather than imply capacity.
 */
export type PlanRecommendationBasis = 'same-plan' | 'weighted' | 'percentage';

/** Which account has the most room, and what decides it. */
export interface PlanRecommendation {
  readonly profileId: ProfileId;
  /** Percentage of the tightest window still unused, 0–100. */
  readonly headroom: number;
  /**
   * The window that sets that number — the limit that would stop this account
   * first. Carried so the UI can name it: "68% free · 5 hours" says something
   * "68% free" does not, because the two windows reset hours apart.
   */
  readonly binding: PlanUsageWindow;
  /** How many accounts it was chosen from. Never less than two — see below. */
  readonly candidates: number;
  /** The winner's plan tier as the provider names it, when it names one. */
  readonly subscriptionType?: string;
  /**
   * The winner's plan, when one could be identified. `Max 20x` rather than the
   * provider's bare `max` — which is the whole point of pinning it.
   */
  readonly plan?: PlanCapacity;
  /**
   * True when the winner's tier was inferred from an ambiguous reported string
   * rather than pinned on the profile.
   *
   * Both providers report a plan *family*: `max` covers Max 5x and Max 20x,
   * `pro` covers both Codex Pro tiers, and the members differ fourfold. The
   * inference takes the floor of the family, so an assumed weight understates
   * an account and never flatters it — but a ranking resting on one is a
   * ranking the user can improve by telling Artemis which plan it actually is.
   */
  readonly assumedPlan: boolean;
  /**
   * What the comparison was able to be. See {@link PlanRecommendationBasis} —
   * the UI's wording turns on this and must not overstate it.
   */
  readonly basis: PlanRecommendationBasis;
}

/**
 * The account with the most room left, or `null` when that is not a question.
 *
 * ## What is deliberately *not* a candidate
 *
 * **A profile with no plan limits.** An API-key, Bedrock or Vertex profile
 * reports `available: false` because it is metered rather than capped, which
 * reads as "infinite room" and is the single worst thing this could recommend:
 * the answer to "my plan is full" would become "switch to the one that bills
 * per token", silently, at whatever the next turn costs. Excluded outright.
 *
 * **A stale reading.** See {@link PLAN_USAGE_MAX_AGE_MS}. An account that has
 * not been re-read in three poll cycles is not evidence about now.
 *
 * **A reading with no usable number.** A plan whose every window reports `null`
 * utilization cannot be ranked against one that reports figures.
 *
 * **An account the user has taken out of the pool.** Not excluded here, and
 * deliberately: `autoSelect` and `disabled` are facts about a *profile*, and
 * this function is given readings. The caller filters with
 * {@link isProfileAutoSelectable} before calling — which is also what makes
 * `candidates` honest, since an account that could never win should not be
 * counted among the ones the winner beat.
 *
 * ## Why two candidates are required
 *
 * With one rankable account there is no choice to make, and a "Recommended"
 * heading over the only profile that has a plan is a recommendation in form
 * only — it repeats the row below it and the meter beside it. The section earns
 * its space the moment a second account exists, which is also the first moment
 * switching is a thing the user can do.
 *
 * Ties keep the caller's order rather than being broken arbitrarily: two
 * accounts at exactly the same headroom would otherwise swap the label between
 * them on alternating polls, which reads as churn rather than as a tie.
 *
 * ## How the winner is chosen
 *
 * Two passes, because the *basis* has to be settled before the ranking can be:
 * whether a plan's published size may be used depends on every other candidate
 * having one too, and on all of them being the same provider's. Ranking by
 * weight and then discovering the set was unweighable would leave a winner
 * chosen on a rule the UI is about to say it did not use.
 *
 * With a basis of `weighted`, accounts are ordered by `headroom × weight` —
 * percentage-points of the provider's *baseline* plan. A Max 20x at 30% free
 * scores 600 against a Pro at 90% free scoring 90, which is the comparison the
 * bare percentages invert. Otherwise the order is headroom alone.
 */
export function recommendProfile(
  entries: readonly ProfilePlanUsage[],
  options: { readonly now: number; readonly maxAgeMs?: number },
): PlanRecommendation | null {
  const maxAge = options.maxAgeMs ?? PLAN_USAGE_MAX_AGE_MS;

  /** Everything that survived the exclusions, with what it needs to be ranked. */
  const ranked: {
    readonly entry: ProfilePlanUsage;
    readonly usage: PlanUsage;
    readonly binding: PlanUsageWindow;
    readonly headroom: number;
  }[] = [];

  for (const entry of entries) {
    const usage = entry.usage;
    if (!usage?.available) continue;
    // A reading from the future is a clock that disagrees with itself, not a
    // fresh one — `now - fetchedAt` is clamped at zero rather than negative so
    // such a reading is treated as current instead of infinitely stale.
    if (Math.max(0, options.now - usage.fetchedAt) > maxAge) continue;

    const binding = bindingWindow(usage);
    if (binding === null) continue;
    // The same rule as {@link planHeadroom}: a rejected window is zero room
    // whatever it reads. It stays *in* the ranking rather than being excluded —
    // an account the provider is refusing is a fact worth counting among the
    // candidates the winner beat, and at zero it can never be named.
    const headroom = binding.status === 'rejected' ? 0 : 100 - (binding.utilization ?? NaN);
    if (Number.isNaN(headroom)) continue;

    ranked.push({ entry, usage, binding, headroom });
  }

  if (ranked.length < 2) return null;

  const basis = basisFor(ranked.map((r) => r.entry));

  let best = ranked[0];
  if (best === undefined) return null;
  for (const candidate of ranked.slice(1)) {
    // Strictly greater: the first entry at a given score keeps the title, which
    // is what stops two tied accounts trading the label on alternating polls.
    if (scoreOf(candidate, basis) > scoreOf(best, basis)) best = candidate;
  }

  const capacity = best.entry.capacity ?? null;
  return {
    profileId: best.entry.profileId,
    headroom: best.headroom,
    binding: best.binding,
    candidates: ranked.length,
    assumedPlan: capacity?.assumed ?? false,
    basis,
    ...(best.usage.subscriptionType === undefined
      ? {}
      : { subscriptionType: best.usage.subscriptionType }),
    ...(capacity === null ? {} : { plan: capacity.plan }),
  };
}

/**
 * Headroom, scaled by plan size, less what the live runs have already claimed.
 *
 * ## Why the reservation is subtracted in the *weighted* space
 *
 * `reservationFor` answers in percentage points of a **baseline** plan's window,
 * and headroom is a percentage of *this* account's. Those are different units
 * the moment two plans differ in size: one Fable/ultracode session eats a
 * quarter as much of a Max 20x window as it does of a Max 5x one.
 *
 * Multiplying headroom by the plan weight converts it to baseline points, which
 * is exactly the space the reservation is already in — so the subtraction is a
 * subtraction of like from like, and no per-account division is needed.
 *
 * This is why `same-plan` now scales too, where it previously returned raw
 * headroom. Every candidate shares one plan there, so a common multiplier
 * changes no ordering between them; what it changes is that the reservation
 * lands on the right scale instead of being over-subtracted by the plan's own
 * weight. A Max 20x account would otherwise have one live session wipe out
 * twenty times more headroom than that session actually costs it.
 *
 * Under `percentage` the weights are not trusted *between* accounts — that is
 * what the basis means — so the ranking stays on raw shares. The reservation is
 * still divided by the account's own weight where it has one, which is a
 * correction within a single account rather than a comparison across two, and
 * makes each number less wrong without claiming the set is comparable.
 *
 * ## Nothing is clamped
 *
 * A score may go negative, and that is deliberate. Clamping at zero would tie
 * every over-committed account at "no room", and the winner among them would
 * fall to list order — quite possibly the most loaded one. Letting them go
 * negative keeps the *least* over-committed account on top, which is the honest
 * answer to "where should this go" when the true answer is "nowhere good".
 */
function scoreOf(
  candidate: { readonly entry: ProfilePlanUsage; readonly headroom: number },
  basis: PlanRecommendationBasis,
): number {
  const weight = candidate.entry.capacity?.weight ?? 1;
  const reserved = reservationFor(candidate.entry.liveRuns);
  if (basis === 'percentage') return candidate.headroom - reserved / weight;
  return candidate.headroom * weight - reserved;
}

/**
 * What this set of accounts can honestly be compared on.
 *
 * The order of the tests is the order of the claims, strongest first. Note that
 * `same-plan` outranks `weighted` even though both are true comparisons: two
 * accounts on one plan need no ratio at all, so saying "most room" is both
 * stronger and simpler than saying it after multiplying everything by the same
 * number.
 */
function basisFor(entries: readonly ProfilePlanUsage[]): PlanRecommendationBasis {
  const plans = new Set<string>();
  const providers = new Set<string>();
  let everyPlanWeighed = true;

  for (const entry of entries) {
    const capacity = entry.capacity ?? null;
    // A plan nobody could identify, or one sold as a seat or a credit pool
    // rather than as a multiple of anything. Either way there is no ratio.
    if (capacity === null || capacity.weight === null) everyPlanWeighed = false;
    plans.add(capacity?.plan.id ?? entry.usage?.subscriptionType?.trim().toLowerCase() ?? 'unknown');
    providers.add(entry.providerId ?? 'unknown');
  }

  if (plans.size === 1 && !plans.has('unknown')) return 'same-plan';
  /*
    Weights are ratios against one provider's baseline plan, and no provider
    publishes a rate between its baseline and another provider's. A Claude Pro
    window and a Codex Plus window both weigh 1 and are not the same size, so a
    mixed-provider set falls back to percentages however well each side is
    documented.
  */
  if (everyPlanWeighed && providers.size === 1 && !providers.has('unknown')) return 'weighted';
  return 'percentage';
}
